#!/usr/bin/env python
import rospy
from std_msgs.msg import Float32MultiArray

def callback(data):
    
    rospy.loginfo(rospy.get_caller_id() + " I received %s", data.data)

def listener():
    
    rospy.init_node('go1_ros', anonymous=False)

    rospy.Subscriber('/dof_obs', Float32MultiArray, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()
